### ISSUE TITLE
[Bug]: calls and videos are always connecting never connected

### ISSUE THREAD

**Issue by basicallynewbie** [simplex-chat/simplex-chat#2798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 12

### App version

5.2

### Current Behavior

I tried to use phone a to call phone b, phone b accepted the offer, then showing connecting, contact has no e2e encryption. So does it happen in video calls.

![Screenshot_20230729_134542](https://github.com/simplex-chat/simplex-chat/assets/107107611/fa92afc6-32ec-4d6b-8d8c-6af2354e16b1)

### Expected Behavior

Phone a calls phone b, and connection established, then they can talk to each other.

### Steps To Reproduce

Phone a press the phone button, the offer already showing no e2e connection, phone b accept the offer, then showing connecting, contact has no e2e encryption.
So I ping turn.simplex.im, failed. Guess China GFW blocked it.
Then I tested some free stun server, still no e2e encryption, never reach connecting state, failed too.
So I selfhost a coturn server to test.Ping succeeded, nc succeeded, icetest.info test succeeded. But still showing connecting, contact has no e2e encryption.
```
version: "3"
services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    command:
      - '--listening-port=3478'
      - '--tls-listening-port=5349'
      - '--min-port=49152'
      - '--max-port=49200'
      #- '--listening-ip=0.0.0.0'
      #- '--relay-ip=0.0.0.0'
      - '--external-ip=mypublicip'
      - '--user=testuser:testpassword'
      - '--realm=mydomain'
      - '--server-name=mydomain'
      - '--cert=/etc/letsencrypt/cert.pem'
      - '--pkey=/etc/letsencrypt/live/privkey.pem'
      - '--verbose'
      - '--fingerprint'
      - '--lt-cred-mech'
      - '--mobility'
      - '--no-cli'
      - '--no-software-attribute'
      - '--no-multicast-peers'
      - '--no-stun-backward-compatibility'
      - '--no-rfc5780'
      #- '--response-origin-only-with-rfc5780'
      - '--cipher-list=ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
      #- '--no-tlsv1'
      #- '--no-tlsv1_1'
      #- '--no-tlsv1_2'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/letsencrypt/certs/live/mydomain/cert.pem:/etc/letsencrypt/cert.pem:ro
      - /etc/letsencrypt/certs/live/mydomain/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    network_mode: 'host'
```

**Comment by basicallynewbie** [comment]
I have tweaked coturn several times. Even get rid of domains. Yes, icetest.info test succeeded. But still no luck.
The docker compose now looks like this:
```
version: "3"
services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    command:
      - '--listening-port=3478'
      - '--tls-listening-port=5349'
      - '--min-port=49152'
      - '--max-port=49200'
      - '--external-ip=mypublicip'
      - '--user=testuser:testpassword'
      - '--lt-cred-mech'
      - '--mobility'
      - '--no-cli'
    network_mode: 'host'
```
I really don't think coturn is the problem. Could it be my smp server goes wrong? But the "view security code" in user page is verified.
Docker compose:
```
version: "3"
services:
  smp-server:
    image: simplexchat/smp-server:latest
    container_name: smp-server
    environment:
      - ADDR=smp.Mydomain
      - PASS=testpassword
    volumes:
      - /etc/simplex/smp/config:/etc/opt/simplex:z
      - /etc/simplex/smp/logs:/var/opt/simplex:z
    ports:
      - 5223:5223 
    restart: unless-stopped
```
