### ISSUE TITLE
[Feature]: Sign all future releases with PGP 

### ISSUE THREAD

**Issue by groovy-boiler** [simplex-chat/simplex-chat#5417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

all

## Generate a signing-key 
Generate a project signing key so that people can verify the integrity of the downloads.
This is common practice among privacy and security projects and most if not all linux package managers manually check GPG of signed releases.

This is something that should be done and keep in mind if the packages where ever to be added to AUR or APT repository this would have to be done anyway.

**Best practices**:

1. **Use an Air-Gapped Computer to generate a key**
   - Use a live system to generate the key.
   - You can generate it in RAM by making sure `/tmp` is mounted to `/tmpfs`.
     - Generate Key in `/tmp`:
       ```bash
       gpg --full-generate-key --homedir=/tmp/.gnupg/
       ```
     - Export Key to mounted USB drive:
       ```bash
       gpg --homedir=/tmp/.gnupg/ --armor --export <your-email@example.com> > /media/user/USB_DRIVE/public_key.asc
       ```
       (Make sure key ID `<your-email@example.com>` is correct and the user and `USB_DRIVE` is correct, e.g., `/dev/sdb`.)

2. **Limit Key Usage**
   - *Signing Only*: If the key is only used for signing, ensure that it is not used for encryption or other purposes. This limits exposure and potential misuse.
   - *Subkeys*: Consider using subkeys for different purposes (e.g., one for signing, one for encryption). This allows you to revoke a subkey without affecting the primary key.

3. **Public Key Distribution**
   - *Secure Distribution*: When distributing the public key, ensure it is done securely. Use trusted channels and verify the integrity of the key.
   - Store it in different places to avoid a single point of failure (e.g., GitHub and your website).

### Automatically with *GitHub Actions*

**GitHub Action Workflow:** `release.yml`

```yaml
name: Release

on:
  release:
    types: [published]

jobs:
  generate-checksums-and-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --yes

      - name: Generate checksums
        run: |
          # Create SHA256SUMS.txt with checksums for all files in the release
          echo "Generating SHA256SUMS.txt..."
          for file in ${{ github.event.release.assets.*.name }}; do
            sha256sum "$file" >> SHA256SUMS.txt
          done

      - name: Clear-sign checksums
        run: |
          echo "Clear-signing SHA256SUMS.txt..."
          gpg --clearsign SHA256SUMS.txt -o SHA256SUMS

      - name: Upload checksums and signature
        uses: actions/upload-artifact@v2
        with:
          name: checksums-and-signature
          path: SHA256SUMS
```
